[package]
name = "stuff"
version = "0.1.0"
edition = "2021"
default-run = "epa_test"

[lib]
name = "stuff_lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
three-d = "0.17"
itertools = "0.10.0"
